apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  chart:
    spec:
      chart: nginx
      version: "latest" # Use the specific version of the Nginx Helm chart you want to deploy
      sourceRef:
        kind: HelmRepository
        name: stable # This should match the name of the HelmRepository resource that points to the chart's repository
        namespace: default
  interval: 1m
  values:
    replicaCount: 2
    service:
      type: ClusterIP
    ingress:
      enabled: false # We disable the default ingress because we'll use Traefik's IngressRoute

